- hosts: all
  become: yes
  tasks:
    - name: create the 'ansk8s' user
      user: name=ansk8s append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'ansk8s' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'ansk8s ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ansk8s user
      authorized_key: user=ansk8s key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
